version: '3'
services:
  web:
    build: .
    tty: true
    stdin_open: true
    environment:
      - SLACK_API_TOKEN
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle
volumes:
  bundle-data:
    driver: local
